#!/usr/bin/env python3
"""
live_predict.py — Phases 10 & 11

Daemon script that polls the live features generated by the monitor,
evaluates the Soft Voting Ensemble to compute a deadlock risk score,
and triggers early auto-resolution if the risk crosses a threshold.
"""

import os
import time
import json
import joblib
import pandas as pd
from datetime import datetime

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
MODEL_PATH = os.path.join(ROOT_DIR, 'predictor', 'models', 'deadlock_predictor.pkl')
FEATURES_PATH = os.path.join(ROOT_DIR, 'status', 'features.json')
RISK_PATH = os.path.join(ROOT_DIR, 'status', 'risk.json')
RESOLVE_TRIGGER_PATH = "/tmp/deadlock_guard.resolve"

# Threshold for early auto-resolution
RISK_THRESHOLD = 0.75
POLL_INTERVAL = 0.2  # seconds

def read_features():
    if not os.path.exists(FEATURES_PATH):
        return None
    try:
        with open(FEATURES_PATH, 'r') as f:
            return json.load(f)
    except:
        return None

def write_risk(score, action_taken):
    try:
        with open(RISK_PATH, 'w') as f:
            json.dump({
                "timestamp": datetime.now().isoformat(),
                "risk_score": float(score),
                "action": action_taken
            }, f)
    except Exception as e:
        print(f"[live_predict] Failed to write risk: {e}")

def trigger_resolution():
    """Phase 11: Auto-resolve on high risk via trigger file"""
    try:
        with open(RESOLVE_TRIGGER_PATH, 'w') as f:
            f.write("1")
        print(f"\n[live_predict] 🚨 HIGH RISK DETECTED — Triggered early auto-resolution!")
    except Exception as e:
        print(f"[live_predict] Failed to trigger resolution: {e}")

def main():
    if not os.path.exists(MODEL_PATH):
        print(f"[live_predict] Model not found at {MODEL_PATH}. Run train_model.py first.")
        return

    print("[live_predict] Loading Soft Voting Ensemble model...")
    model = joblib.load(MODEL_PATH)
    print("[live_predict] Model loaded. Polling for live features...")

    last_features = None

    try:
        while True:
            features = read_features()
            if features is not None and features != last_features:
                last_features = features
                
                # Prepare data frame for prediction
                df = pd.DataFrame([features])[
                    ['blocked_count', 'wait_time_growth', 'edge_count', 'graph_density']
                ]
                
                # predict_proba returns probabilities for classes [0, 1]
                # We want the probability of class 1 (Deadlock)
                probas = model.predict_proba(df)
                risk_score = probas[0][1]
                
                print(f"[live_predict] Blocked: {features['blocked_count']}, "
                      f"Edges: {features['edge_count']}, "
                      f"Density: {features['graph_density']:.2f} "
                      f"--> Risk Score: {risk_score:.2f}")

                action_taken = "none"
                if risk_score >= RISK_THRESHOLD:
                    trigger_resolution()
                    action_taken = "triggered_resolution"
                
                write_risk(risk_score, action_taken)

            time.sleep(POLL_INTERVAL)
            
    except KeyboardInterrupt:
        print("\n[live_predict] Exiting...")

if __name__ == "__main__":
    main()
